title: Zhehao Zhang
tagline: PhD Student in Computer Science at The Ohio State University
url: https://zhehaozhang123.github.io
baseurl: ""
# gems: [jekyll-paginate]
# paginate: 5

# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink: "/:title"
# relative_permalinks: true

sass:
  sass_dir: _sass
  style: compressed

author:
  name: Zhehao Zhang
  url: https://zhehaozhang123.github.io
  email: zhehao.zhang.gr@dartmouth.edu

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: 'syntax'

excerpt_separator: <!--more-->

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
